; Auto-generated. Do not edit!


(cl:in-package gen5-msg)


;//! \htmlinclude RotateFeedback.msg.html

(cl:defclass <RotateFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RotateFeedback (<RotateFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotateFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotateFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gen5-msg:<RotateFeedback> is deprecated: use gen5-msg:RotateFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotateFeedback>) ostream)
  "Serializes a message object of type '<RotateFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotateFeedback>) istream)
  "Deserializes a message object of type '<RotateFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotateFeedback>)))
  "Returns string type for a message object of type '<RotateFeedback>"
  "gen5/RotateFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotateFeedback)))
  "Returns string type for a message object of type 'RotateFeedback"
  "gen5/RotateFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotateFeedback>)))
  "Returns md5sum for a message object of type '<RotateFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotateFeedback)))
  "Returns md5sum for a message object of type 'RotateFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotateFeedback>)))
  "Returns full string definition for message of type '<RotateFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotateFeedback)))
  "Returns full string definition for message of type 'RotateFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotateFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotateFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RotateFeedback
))
