; Auto-generated. Do not edit!


(cl:in-package gen5-msg)


;//! \htmlinclude RunFeedback.msg.html

(cl:defclass <RunFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RunFeedback (<RunFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RunFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RunFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gen5-msg:<RunFeedback> is deprecated: use gen5-msg:RunFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RunFeedback>) ostream)
  "Serializes a message object of type '<RunFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RunFeedback>) istream)
  "Deserializes a message object of type '<RunFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RunFeedback>)))
  "Returns string type for a message object of type '<RunFeedback>"
  "gen5/RunFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RunFeedback)))
  "Returns string type for a message object of type 'RunFeedback"
  "gen5/RunFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RunFeedback>)))
  "Returns md5sum for a message object of type '<RunFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RunFeedback)))
  "Returns md5sum for a message object of type 'RunFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RunFeedback>)))
  "Returns full string definition for message of type '<RunFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RunFeedback)))
  "Returns full string definition for message of type 'RunFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RunFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RunFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RunFeedback
))
