; Auto-generated. Do not edit!


(cl:in-package gen5-msg)


;//! \htmlinclude RunResult.msg.html

(cl:defclass <RunResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RunResult (<RunResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RunResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RunResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gen5-msg:<RunResult> is deprecated: use gen5-msg:RunResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RunResult>) ostream)
  "Serializes a message object of type '<RunResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RunResult>) istream)
  "Deserializes a message object of type '<RunResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RunResult>)))
  "Returns string type for a message object of type '<RunResult>"
  "gen5/RunResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RunResult)))
  "Returns string type for a message object of type 'RunResult"
  "gen5/RunResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RunResult>)))
  "Returns md5sum for a message object of type '<RunResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RunResult)))
  "Returns md5sum for a message object of type 'RunResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RunResult>)))
  "Returns full string definition for message of type '<RunResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RunResult)))
  "Returns full string definition for message of type 'RunResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RunResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RunResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RunResult
))
