// Auto-generated. Do not edit!

// (in-package robot_services.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class RotateFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.rotation_completed = null;
    }
    else {
      if (initObj.hasOwnProperty('rotation_completed')) {
        this.rotation_completed = initObj.rotation_completed
      }
      else {
        this.rotation_completed = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RotateFeedback
    // Serialize message field [rotation_completed]
    bufferOffset = _serializer.float32(obj.rotation_completed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RotateFeedback
    let len;
    let data = new RotateFeedback(null);
    // Deserialize message field [rotation_completed]
    data.rotation_completed = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_services/RotateFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9cefb4e1ca23db842009caa7fcf3ff37';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float32 rotation_completed
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RotateFeedback(null);
    if (msg.rotation_completed !== undefined) {
      resolved.rotation_completed = msg.rotation_completed;
    }
    else {
      resolved.rotation_completed = 0.0
    }

    return resolved;
    }
};

module.exports = RotateFeedback;
