// Generated by gencpp from file mygopigo/SPI.msg
// DO NOT EDIT!


#ifndef MYGOPIGO_MESSAGE_SPI_H
#define MYGOPIGO_MESSAGE_SPI_H

#include <ros/service_traits.h>


#include <mygopigo/SPIRequest.h>
#include <mygopigo/SPIResponse.h>


namespace mygopigo
{

struct SPI
{

typedef SPIRequest Request;
typedef SPIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SPI
} // namespace mygopigo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mygopigo::SPI > {
  static const char* value()
  {
    return "e04010cc40eb2ab4db306dc8c290e92b";
  }

  static const char* value(const ::mygopigo::SPI&) { return value(); }
};

template<>
struct DataType< ::mygopigo::SPI > {
  static const char* value()
  {
    return "mygopigo/SPI";
  }

  static const char* value(const ::mygopigo::SPI&) { return value(); }
};


// service_traits::MD5Sum< ::mygopigo::SPIRequest> should match
// service_traits::MD5Sum< ::mygopigo::SPI >
template<>
struct MD5Sum< ::mygopigo::SPIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mygopigo::SPI >::value();
  }
  static const char* value(const ::mygopigo::SPIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mygopigo::SPIRequest> should match
// service_traits::DataType< ::mygopigo::SPI >
template<>
struct DataType< ::mygopigo::SPIRequest>
{
  static const char* value()
  {
    return DataType< ::mygopigo::SPI >::value();
  }
  static const char* value(const ::mygopigo::SPIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mygopigo::SPIResponse> should match
// service_traits::MD5Sum< ::mygopigo::SPI >
template<>
struct MD5Sum< ::mygopigo::SPIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mygopigo::SPI >::value();
  }
  static const char* value(const ::mygopigo::SPIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mygopigo::SPIResponse> should match
// service_traits::DataType< ::mygopigo::SPI >
template<>
struct DataType< ::mygopigo::SPIResponse>
{
  static const char* value()
  {
    return DataType< ::mygopigo::SPI >::value();
  }
  static const char* value(const ::mygopigo::SPIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYGOPIGO_MESSAGE_SPI_H
