// Generated by gencpp from file mygopigo/SPIRequest.msg
// DO NOT EDIT!


#ifndef MYGOPIGO_MESSAGE_SPIREQUEST_H
#define MYGOPIGO_MESSAGE_SPIREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mygopigo
{
template <class ContainerAllocator>
struct SPIRequest_
{
  typedef SPIRequest_<ContainerAllocator> Type;

  SPIRequest_()
    : data_out()  {
    }
  SPIRequest_(const ContainerAllocator& _alloc)
    : data_out(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_out_type;
  _data_out_type data_out;





  typedef boost::shared_ptr< ::mygopigo::SPIRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mygopigo::SPIRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SPIRequest_

typedef ::mygopigo::SPIRequest_<std::allocator<void> > SPIRequest;

typedef boost::shared_ptr< ::mygopigo::SPIRequest > SPIRequestPtr;
typedef boost::shared_ptr< ::mygopigo::SPIRequest const> SPIRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mygopigo::SPIRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mygopigo::SPIRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mygopigo::SPIRequest_<ContainerAllocator1> & lhs, const ::mygopigo::SPIRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data_out == rhs.data_out;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mygopigo::SPIRequest_<ContainerAllocator1> & lhs, const ::mygopigo::SPIRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mygopigo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mygopigo::SPIRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mygopigo::SPIRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mygopigo::SPIRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mygopigo::SPIRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mygopigo::SPIRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mygopigo::SPIRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mygopigo::SPIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "561ae924966a6e65b3e6723a081d160a";
  }

  static const char* value(const ::mygopigo::SPIRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x561ae924966a6e65ULL;
  static const uint64_t static_value2 = 0xb3e6723a081d160aULL;
};

template<class ContainerAllocator>
struct DataType< ::mygopigo::SPIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mygopigo/SPIRequest";
  }

  static const char* value(const ::mygopigo::SPIRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mygopigo::SPIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] data_out    # sent byte array\n"
;
  }

  static const char* value(const ::mygopigo::SPIRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mygopigo::SPIRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data_out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SPIRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mygopigo::SPIRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mygopigo::SPIRequest_<ContainerAllocator>& v)
  {
    s << indent << "data_out[]" << std::endl;
    for (size_t i = 0; i < v.data_out.size(); ++i)
    {
      s << indent << "  data_out[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data_out[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYGOPIGO_MESSAGE_SPIREQUEST_H
