// Generated by gencpp from file robot_services/RotateResult.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVICES_MESSAGE_ROTATERESULT_H
#define ROBOT_SERVICES_MESSAGE_ROTATERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_services
{
template <class ContainerAllocator>
struct RotateResult_
{
  typedef RotateResult_<ContainerAllocator> Type;

  RotateResult_()
    : time_taken(0.0)  {
    }
  RotateResult_(const ContainerAllocator& _alloc)
    : time_taken(0.0)  {
  (void)_alloc;
    }



   typedef float _time_taken_type;
  _time_taken_type time_taken;





  typedef boost::shared_ptr< ::robot_services::RotateResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_services::RotateResult_<ContainerAllocator> const> ConstPtr;

}; // struct RotateResult_

typedef ::robot_services::RotateResult_<std::allocator<void> > RotateResult;

typedef boost::shared_ptr< ::robot_services::RotateResult > RotateResultPtr;
typedef boost::shared_ptr< ::robot_services::RotateResult const> RotateResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_services::RotateResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_services::RotateResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_services::RotateResult_<ContainerAllocator1> & lhs, const ::robot_services::RotateResult_<ContainerAllocator2> & rhs)
{
  return lhs.time_taken == rhs.time_taken;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_services::RotateResult_<ContainerAllocator1> & lhs, const ::robot_services::RotateResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_services::RotateResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_services::RotateResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_services::RotateResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_services::RotateResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_services::RotateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_services::RotateResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_services::RotateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb94241e261749226844ca094b5ee0a2";
  }

  static const char* value(const ::robot_services::RotateResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb94241e26174922ULL;
  static const uint64_t static_value2 = 0x6844ca094b5ee0a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_services::RotateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_services/RotateResult";
  }

  static const char* value(const ::robot_services::RotateResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_services::RotateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 time_taken\n"
;
  }

  static const char* value(const ::robot_services::RotateResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_services::RotateResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_taken);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RotateResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_services::RotateResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_services::RotateResult_<ContainerAllocator>& v)
  {
    s << indent << "time_taken: ";
    Printer<float>::stream(s, indent + "  ", v.time_taken);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SERVICES_MESSAGE_ROTATERESULT_H
