// Generated by gencpp from file robot_services/RotateGoal.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVICES_MESSAGE_ROTATEGOAL_H
#define ROBOT_SERVICES_MESSAGE_ROTATEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_services
{
template <class ContainerAllocator>
struct RotateGoal_
{
  typedef RotateGoal_<ContainerAllocator> Type;

  RotateGoal_()
    : rads_to_turn(0.0)  {
    }
  RotateGoal_(const ContainerAllocator& _alloc)
    : rads_to_turn(0.0)  {
  (void)_alloc;
    }



   typedef float _rads_to_turn_type;
  _rads_to_turn_type rads_to_turn;





  typedef boost::shared_ptr< ::robot_services::RotateGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_services::RotateGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RotateGoal_

typedef ::robot_services::RotateGoal_<std::allocator<void> > RotateGoal;

typedef boost::shared_ptr< ::robot_services::RotateGoal > RotateGoalPtr;
typedef boost::shared_ptr< ::robot_services::RotateGoal const> RotateGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_services::RotateGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_services::RotateGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_services::RotateGoal_<ContainerAllocator1> & lhs, const ::robot_services::RotateGoal_<ContainerAllocator2> & rhs)
{
  return lhs.rads_to_turn == rhs.rads_to_turn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_services::RotateGoal_<ContainerAllocator1> & lhs, const ::robot_services::RotateGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_services::RotateGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_services::RotateGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_services::RotateGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_services::RotateGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_services::RotateGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_services::RotateGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_services::RotateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d004314c61590cdf48db27002978bbb1";
  }

  static const char* value(const ::robot_services::RotateGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd004314c61590cdfULL;
  static const uint64_t static_value2 = 0x48db27002978bbb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_services::RotateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_services/RotateGoal";
  }

  static const char* value(const ::robot_services::RotateGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_services::RotateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal \n"
"float32 rads_to_turn\n"
;
  }

  static const char* value(const ::robot_services::RotateGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_services::RotateGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rads_to_turn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RotateGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_services::RotateGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_services::RotateGoal_<ContainerAllocator>& v)
  {
    s << indent << "rads_to_turn: ";
    Printer<float>::stream(s, indent + "  ", v.rads_to_turn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SERVICES_MESSAGE_ROTATEGOAL_H
