// Generated by gencpp from file gen5/RotateResult.msg
// DO NOT EDIT!


#ifndef GEN5_MESSAGE_ROTATERESULT_H
#define GEN5_MESSAGE_ROTATERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gen5
{
template <class ContainerAllocator>
struct RotateResult_
{
  typedef RotateResult_<ContainerAllocator> Type;

  RotateResult_()
    {
    }
  RotateResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::gen5::RotateResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gen5::RotateResult_<ContainerAllocator> const> ConstPtr;

}; // struct RotateResult_

typedef ::gen5::RotateResult_<std::allocator<void> > RotateResult;

typedef boost::shared_ptr< ::gen5::RotateResult > RotateResultPtr;
typedef boost::shared_ptr< ::gen5::RotateResult const> RotateResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gen5::RotateResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gen5::RotateResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace gen5

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gen5::RotateResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gen5::RotateResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gen5::RotateResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gen5::RotateResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gen5::RotateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gen5::RotateResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gen5::RotateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gen5::RotateResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::gen5::RotateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gen5/RotateResult";
  }

  static const char* value(const ::gen5::RotateResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gen5::RotateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
;
  }

  static const char* value(const ::gen5::RotateResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gen5::RotateResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RotateResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gen5::RotateResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::gen5::RotateResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GEN5_MESSAGE_ROTATERESULT_H
