// Generated by gencpp from file gen5/RotateGoal.msg
// DO NOT EDIT!


#ifndef GEN5_MESSAGE_ROTATEGOAL_H
#define GEN5_MESSAGE_ROTATEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gen5
{
template <class ContainerAllocator>
struct RotateGoal_
{
  typedef RotateGoal_<ContainerAllocator> Type;

  RotateGoal_()
    : degrees_to_rotate(0.0)
    , angular_velocity(0.0)  {
    }
  RotateGoal_(const ContainerAllocator& _alloc)
    : degrees_to_rotate(0.0)
    , angular_velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _degrees_to_rotate_type;
  _degrees_to_rotate_type degrees_to_rotate;

   typedef float _angular_velocity_type;
  _angular_velocity_type angular_velocity;





  typedef boost::shared_ptr< ::gen5::RotateGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gen5::RotateGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RotateGoal_

typedef ::gen5::RotateGoal_<std::allocator<void> > RotateGoal;

typedef boost::shared_ptr< ::gen5::RotateGoal > RotateGoalPtr;
typedef boost::shared_ptr< ::gen5::RotateGoal const> RotateGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gen5::RotateGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gen5::RotateGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gen5::RotateGoal_<ContainerAllocator1> & lhs, const ::gen5::RotateGoal_<ContainerAllocator2> & rhs)
{
  return lhs.degrees_to_rotate == rhs.degrees_to_rotate &&
    lhs.angular_velocity == rhs.angular_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gen5::RotateGoal_<ContainerAllocator1> & lhs, const ::gen5::RotateGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gen5

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gen5::RotateGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gen5::RotateGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gen5::RotateGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gen5::RotateGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gen5::RotateGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gen5::RotateGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gen5::RotateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5a9b914cd60c234ba8daecd329575c6";
  }

  static const char* value(const ::gen5::RotateGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5a9b914cd60c234ULL;
  static const uint64_t static_value2 = 0xba8daecd329575c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::gen5::RotateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gen5/RotateGoal";
  }

  static const char* value(const ::gen5::RotateGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gen5::RotateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Part 1: the goal, to be sent by the client\n"
"#\n"
"# Degree the robots need to rotate and the velocity\n"
"float32 degrees_to_rotate\n"
"float32 angular_velocity\n"
;
  }

  static const char* value(const ::gen5::RotateGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gen5::RotateGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.degrees_to_rotate);
      stream.next(m.angular_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RotateGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gen5::RotateGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gen5::RotateGoal_<ContainerAllocator>& v)
  {
    s << indent << "degrees_to_rotate: ";
    Printer<float>::stream(s, indent + "  ", v.degrees_to_rotate);
    s << indent << "angular_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.angular_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEN5_MESSAGE_ROTATEGOAL_H
