// Generated by gencpp from file gen5/RunGoal.msg
// DO NOT EDIT!


#ifndef GEN5_MESSAGE_RUNGOAL_H
#define GEN5_MESSAGE_RUNGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gen5
{
template <class ContainerAllocator>
struct RunGoal_
{
  typedef RunGoal_<ContainerAllocator> Type;

  RunGoal_()
    : distance(0.0)
    , linear_velocity(0.0)  {
    }
  RunGoal_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , linear_velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;

   typedef float _linear_velocity_type;
  _linear_velocity_type linear_velocity;





  typedef boost::shared_ptr< ::gen5::RunGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gen5::RunGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RunGoal_

typedef ::gen5::RunGoal_<std::allocator<void> > RunGoal;

typedef boost::shared_ptr< ::gen5::RunGoal > RunGoalPtr;
typedef boost::shared_ptr< ::gen5::RunGoal const> RunGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gen5::RunGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gen5::RunGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gen5::RunGoal_<ContainerAllocator1> & lhs, const ::gen5::RunGoal_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance &&
    lhs.linear_velocity == rhs.linear_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gen5::RunGoal_<ContainerAllocator1> & lhs, const ::gen5::RunGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gen5

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gen5::RunGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gen5::RunGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gen5::RunGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gen5::RunGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gen5::RunGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gen5::RunGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gen5::RunGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2cc742ee762652d25aed3f303f510d6";
  }

  static const char* value(const ::gen5::RunGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2cc742ee762652dULL;
  static const uint64_t static_value2 = 0x25aed3f303f510d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::gen5::RunGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gen5/RunGoal";
  }

  static const char* value(const ::gen5::RunGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gen5::RunGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Part 1: the goal, to be sent by the client\n"
"#\n"
"# Degree the robots need to rotate and the velocity\n"
"float32 distance\n"
"float32 linear_velocity\n"
;
  }

  static const char* value(const ::gen5::RunGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gen5::RunGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.linear_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RunGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gen5::RunGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gen5::RunGoal_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "linear_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.linear_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GEN5_MESSAGE_RUNGOAL_H
