(cl:in-package prrexamples-msg)
(cl:export '(NARROW_L1-VAL
          NARROW_L1
          NARROW_L2-VAL
          NARROW_L2
          NARROW_L3-VAL
          NARROW_L3
          NARROW_R1-VAL
          NARROW_R1
          NARROW_R2-VAL
          NARROW_R2
          NARROW_R3-VAL
          NARROW_R3
          FORWARD-VAL
          FORWARD
          LEFT-VAL
          LEFT
          RIGHT-VAL
          RIGHT
          BACK-VAL
          BACK
          CLOSEST_DIST-VAL
          CLOSEST_DIST
          CLOSEST_DIR-VAL
          CLOSEST_DIR
          NORM_BEARING-VAL
          NORM_BEARING
          NORM_DIST-VAL
          NORM_DIST
))