(cl:defpackage robot_services-msg
  (:use )
  (:export
   "<ROTATEACTION>"
   "ROTATEACTION"
   "<ROTATEACTIONFEEDBACK>"
   "ROTATEACTIONFEEDBACK"
   "<ROTATEACTIONGOAL>"
   "ROTATEACTIONGOAL"
   "<ROTATEACTIONRESULT>"
   "ROTATEACTIONRESULT"
   "<ROTATEFEEDBACK>"
   "ROTATEFEEDBACK"
   "<ROTATEGOAL>"
   "ROTATEGOAL"
   "<ROTATERESULT>"
   "ROTATERESULT"
  ))

