; Auto-generated. Do not edit!


(cl:in-package robot_services-msg)


;//! \htmlinclude RotateGoal.msg.html

(cl:defclass <RotateGoal> (roslisp-msg-protocol:ros-message)
  ((rads_to_turn
    :reader rads_to_turn
    :initarg :rads_to_turn
    :type cl:float
    :initform 0.0))
)

(cl:defclass RotateGoal (<RotateGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotateGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotateGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_services-msg:<RotateGoal> is deprecated: use robot_services-msg:RotateGoal instead.")))

(cl:ensure-generic-function 'rads_to_turn-val :lambda-list '(m))
(cl:defmethod rads_to_turn-val ((m <RotateGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_services-msg:rads_to_turn-val is deprecated.  Use robot_services-msg:rads_to_turn instead.")
  (rads_to_turn m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotateGoal>) ostream)
  "Serializes a message object of type '<RotateGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'rads_to_turn))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotateGoal>) istream)
  "Deserializes a message object of type '<RotateGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'rads_to_turn) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotateGoal>)))
  "Returns string type for a message object of type '<RotateGoal>"
  "robot_services/RotateGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotateGoal)))
  "Returns string type for a message object of type 'RotateGoal"
  "robot_services/RotateGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotateGoal>)))
  "Returns md5sum for a message object of type '<RotateGoal>"
  "d004314c61590cdf48db27002978bbb1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotateGoal)))
  "Returns md5sum for a message object of type 'RotateGoal"
  "d004314c61590cdf48db27002978bbb1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotateGoal>)))
  "Returns full string definition for message of type '<RotateGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal ~%float32 rads_to_turn~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotateGoal)))
  "Returns full string definition for message of type 'RotateGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal ~%float32 rads_to_turn~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotateGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotateGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RotateGoal
    (cl:cons ':rads_to_turn (rads_to_turn msg))
))
